/**
 * Bun compatibility layer: supplies `stripTypeScriptTypes` for `node:module`.
 *
 * `dsh-code-runtime-worker-thread` uses it to strip type annotations off Code Mode programs; Bun's
 * `node:module` has no such export, so the whole plugin tree fails to start.
 *
 * The critical contract is **byte-length preservation**: the caller wraps the program in
 * `async function __dsh_program__() {\n` … `\n}`, strips it, then slices it back out using the byte
 * lengths of the prefix and suffix. Any transpiler that reorders code (`Bun.Transpiler.transformSync`
 * being one) makes that slice land in the wrong place. amaro's `strip-only` mode replaces types
 * in place with spaces, preserving length — which is exactly what Node's own built-in uses.
 */
import type { ImportRewrite } from './import-rewrite.ts';

/** Filename of the shim written into the backend, placed in the lib/ of the patched package. */
export const SHIM_FILENAME = 'dsh-desktop-strip-shim.js';

/** Packages the shim needs but that no entry can trace. */
export const SHIM_PACKAGES = ['amaro'] as const;

export const STRIP_REWRITE: ImportRewrite = {
  target: '@deepseek-ai/dsh-code-runtime-worker-thread/lib/index.js',
  shimFilename: SHIM_FILENAME,
  pattern: /import\s*\{\s*stripTypeScriptTypes\s*\}\s*from\s*['"]node:module['"]\s*;?/,
  replacement: `import { stripTypeScriptTypes } from "./${SHIM_FILENAME}";`,
  body: { generate: stripShimSource },
  consequence: 'the plugin tree never comes up on Bun',
};

/**
 * `runProfile` unconditionally creates an HMR service, purely to hot-reload the user's
 * `cordis.patch.yml`.
 *
 * HMR reaches for Node's internal module loader, which Bun does not have, so it throws
 * "--expose-internals is required" and kills the process — and it does so *after* the web server
 * has started listening, which is the hardest kind to trace.
 *
 * Changed to "watch only if the composition actually has HMR": the desktop build has no need to
 * edit config while running, a restart is fine. The same condition holds on Node, so both runtimes
 * behave identically.
 */
const HMR_GUARD = 'ctx.fiber.state === 2 && ctx.get("loader") !== void 0) try {';
const HMR_GUARD_PATCHED =
  'ctx.fiber.state === 2 && ctx.get("loader") !== void 0 && ctx.get("hmr") !== void 0) try {';

export function patchProfileBootHmr(source: string): string {
  if (source.includes(HMR_GUARD_PATCHED)) return source;
  if (!source.includes(HMR_GUARD)) {
    throw new Error(
      'no HMR creation condition found in profile-boot — upstream changed the shape, so the ' +
        'Bun compatibility patch must follow rather than be skipped silently.',
    );
  }
  return source.replace(HMR_GUARD, HMR_GUARD_PATCHED);
}

/** This file carries a content hash, so its name changes with every version; match by shape only. */
export function isProfileBootFile(name: string): boolean {
  return /^profile-boot-.*\.js$/.test(name);
}

export function stripShimSource(): string {
  return `// Generated by scripts/bun-shim.ts — do not edit by hand.
// Node 22.6+ ships stripTypeScriptTypes, Bun does not. Both must work, hence the runtime probe.
//
// The fallback must use amaro's 'strip-only': it replaces types in place with equal-length spaces.
// The caller slices by prefix/suffix byte length, so any transpiler that reorders code slices wrong.
import { createRequire } from 'node:module';
import * as builtin from 'node:module';

const require = createRequire(import.meta.url);

/** 3.7 MiB of wasm, loaded only when Code Mode is actually used. */
let amaro;

export function stripTypeScriptTypes(source, options) {
  if (typeof builtin.stripTypeScriptTypes === 'function') {
    return builtin.stripTypeScriptTypes(source, options);
  }
  amaro ??= require('amaro');
  return amaro.transformSync(source, { mode: 'strip-only' }).code;
}
`;
}
