/**
 * PTY adapter: replaces node-pty with Bun's own pseudo-terminal when running on Bun.
 *
 * Under Bun, node-pty's native module **forks the process fine and reports the exit code, but reads
 * not a single byte** (measured: zero `onData` callbacks, while the same code works on Node). The
 * consequence is that the bash / terminal tools silently return an empty string — the command really
 * runs and the user sees nothing.
 *
 * Since Bun 1.3 there is a native PTY (`Bun.spawn({ terminal })`) with semantics equivalent to
 * node-pty. dsh uses only 5 node-pty members, so the adapter surface is tiny:
 *
 *   spawn(file, args, { name, cols, rows, cwd, env })
 *   terminal.pid / .onData(cb) / .onExit(cb) / .write(s) / .kill(sig)
 *
 * No `resize` — upstream genuinely never calls it. If it ever did, it would be silently missing
 * here, which is why the rewrite throws as soon as upstream's import shape changes.
 */
import type { ImportRewrite } from './import-rewrite.ts';

/** Filename of the adapter written into the backend, placed in the lib/ of the patched package. */
export const PTY_SHIM_FILENAME = 'dsh-desktop-pty-shim.js';

export const PTY_REWRITE: ImportRewrite = {
  target: '@deepseek-ai/dsh-subprocess-local/lib/index.js',
  shimFilename: PTY_SHIM_FILENAME,
  pattern: /import\s*\*\s*as\s+nodePty\s+from\s*['"]node-pty['"]\s*;?/,
  replacement: `import * as nodePty from "./${PTY_SHIM_FILENAME}";`,
  body: { generate: ptyShimSource },
  consequence: 'the terminal on Bun silently returns empty output',
};

export function ptyShimSource(): string {
  return `// Generated by scripts/pty-shim.ts — do not edit by hand.
//
// On Bun this uses its native pseudo-terminal; on Node it forwards straight to node-pty. The probe
// happens at runtime, so one artifact runs on both.
import { constants } from 'node:os';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

/** node-pty's onExit reports a **signal number**, not a name: upstream looks it up in os.constants. */
function signalNumber(code) {
  if (code === null || code === undefined) return undefined;
  return constants.signals[code];
}

class BunTerminal {
  #proc;
  // Streaming decode: one multi-byte character may span two reads, and a per-chunk toString() would split it.
  #decoder = new TextDecoder('utf-8');
  #dataListeners = new Set();
  #exitListeners = new Set();
  // The caller registers listeners after spawn, so output from that instant must be retained.
  #pending = [];
  #exit;

  constructor(file, args, options) {
    const env = { ...options.env };
    // node-pty's \`name\` is TERM. Without it, programs assume xterm-256color, which is a behavior
    // change for callers passing \`name: 'dumb'\`.
    if (options.name) env.TERM = options.name;

    this.#proc = Bun.spawn([file, ...args], {
      cwd: options.cwd,
      env,
      terminal: {
        cols: options.cols ?? 80,
        rows: options.rows ?? 24,
        data: (_terminal, chunk) => this.#onChunk(chunk),
      },
    });

    this.#proc.exited.then(() => {
      this.#exit = {
        exitCode: this.#proc.exitCode ?? 0,
        signal: signalNumber(this.#proc.signalCode),
      };
      for (const cb of this.#exitListeners) cb(this.#exit);
    });
  }

  #onChunk(chunk) {
    const text = this.#decoder.decode(chunk, { stream: true });
    if (text.length === 0) return;
    if (this.#dataListeners.size === 0) {
      this.#pending.push(text);
      return;
    }
    for (const cb of this.#dataListeners) cb(text);
  }

  get pid() {
    return this.#proc.pid;
  }

  onData(cb) {
    this.#dataListeners.add(cb);
    const buffered = this.#pending;
    this.#pending = [];
    for (const text of buffered) cb(text);
    return { dispose: () => this.#dataListeners.delete(cb) };
  }

  onExit(cb) {
    this.#exitListeners.add(cb);
    if (this.#exit !== undefined) cb(this.#exit);
    return { dispose: () => this.#exitListeners.delete(cb) };
  }

  write(data) {
    this.#proc.terminal?.write(data);
  }

  kill(signal) {
    // kill throws once the process has exited; to the caller "already dead" and "just killed" are the same.
    try {
      this.#proc.kill(signal ?? 'SIGHUP');
    } catch {}
  }
}

const hasBunTerminal = typeof Bun !== 'undefined' && typeof Bun.Terminal === 'function';

export function spawn(file, args, options) {
  if (hasBunTerminal) return new BunTerminal(file, args ?? [], options ?? {});
  return require('node-pty').spawn(file, args, options);
}
`;
}
